In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
smile_on = pd.read_csv('smileon.csv', low_memory=False)

In [6]:
smile_on.head()

,CallReportNum,ReportVersion,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum,CallerNumCount,PhoneWorkerNum,CityName,CountyName,...,SMILE ON 60+ Screening - Treatment Urgency,SMILE ON 60+ Screening - Untreated Decay,SMILE ON 60+ Site Information - Enroller ID,SMILE ON 60+ Site Information - Enroller Location,SMILE ON 60+ Treatment Plan - Action: Upload After Picture on Finish Tab,SMILE ON 60+ Treatment Plan - Is the treatment plan completed?,SMILE ON 60+ Treatment Plan - Was a treatment plan developed?,"SMILE ON 60+ Treatment Plan - Was the enrollee able to be restored to function (can chew) and ""social six"" esthetics (top front six teeth are present and disease free)",SMILE ON 60+ Verification of Eligibility - Transportation Arranged,SMILE ON 60+ Verification of Eligibility - Verification of Eligibility
0,62945363,SMILE ON 60+ Clinical,5/15/2019 10:00,5/15/2019 11:00,60,-2,10,119473,NaN,NaN,...,NaN,NaN,Healing Hands Health Center - Bristol,NaN,NaN,NaN,Yes,NaN,NaN,NaN
1,57949412,SMILE ON 60+ Clinical,7/1/2018 11:56,7/1/2018 11:59,3,-2,10,116749,NaN,NaN,...,NaN,NaN,Interfaith Dental Clinic - Nashville,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54186032,SMILE ON 60+ Clinical,6/28/2018 9:04,6/28/2018 9:05,1,-2,10,117266,Nashville,Davidson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54184987,SMILE ON 60+ Clinical,6/28/2018 8:21,6/28/2018 8:23,2,-2,10,117266,Nashville,Davidson,...,Urgent Care - within next week-pain or infection,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes
4,54184728,SMILE ON 60+ Registration,6/28/2018 8:09,6/28/2018 8:20,11,-2,10,117266,Nashville,Davidson,...,NaN,NaN,Interfaith Dental Clinic - Nashville,Provider Site,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
phone_worker_num = smile_on[['PhoneWorkerNum', 'EnteredByWorkerNum', 'O2=H2']]
phone_worker_num.head()

   PhoneWorkerNum  EnteredByWorkerNum  O2=H2
0          119473              119473   True
1          116749              116749   True
2          117266              117266   True
3          117266              117266   True
4          117266              117266   True

In [26]:
# o2_h2 = phone_worker_num[phone_worker_num['PhoneWorkerNum'] == 117266]
o2_h2 = phone_worker_num[phone_worker_num['O2=H2'] == False]
o2_h2

       PhoneWorkerNum  EnteredByWorkerNum  O2=H2
117            118820              116749  False
243            118820              117268  False
244            118820              117268  False
259            118820              117268  False
260            118843              116749  False
...               ...                 ...    ...
33451          134403              119515  False
33709          134403              119515  False
33855              -1              133204  False
34212          134403              119515  False
36007          135611              119515  False

[116 rows x 3 columns]