In [1]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
cms_physician = pd.read_csv('../data/cms_physician_and_other_supplier-payments_2015-2017.csv')
#for line in open('u.item', encoding='ISO-8859-1'):
#read each line
cms_physician.columns

Index(['National Provider Identifier',
       'Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider',
       'Credentials of the Provider', 'Gender of the Provider',
       'Entity Type of the Provider', 'Street Address 1 of the Provider',
       'Street Address 2 of the Provider', 'City of the Provider',
       'Zip Code of the Provider', 'State Code of the Provider',
       'Country Code of the Provider', 'Provider Type',
       'Medicare Participation Indicator', 'Place of Service', 'HCPCS Code',
       'HCPCS Description', 'HCPCS Drug Indicator', 'Number of Services',
       'Number of Medicare Beneficiaries',
       'Number of Distinct Medicare Beneficiary/Per Day Services',
       'Average Medicare Allowed Amount', 'Average Submitted Charge Amount',
       'Average Medicare Payment Amount',
       'Average Medicare Standardized Amount'],
      dtype='object')

In [3]:
#drop columns
cms_physician = cms_physician.drop(columns=['First Name of the Provider',
                                            'Last Name/Organization Name of the Provider',
                                            'Middle Initial of the Provider',
                                            'Credentials of the Provider',
                                            'Gender of the Provider',
                                            'Entity Type of the Provider',
                                            'Street Address 1 of the Provider',
                                            'Street Address 2 of the Provider',
                                            'State Code of the Provider',
                                            'Country Code of the Provider',
                                            'Medicare Participation Indicator',
                                            'Place of Service',
                                            'HCPCS Drug Indicator',
                                            'Number of Distinct Medicare Beneficiary/Per Day Services',
                                            'Average Medicare Allowed Amount',
                                            'Average Medicare Standardized Amount'], axis=1)
cms_physician.head()

,National Provider Identifier,City of the Provider,Zip Code of the Provider,Provider Type,HCPCS Code,HCPCS Description,Number of Services,Number of Medicare Beneficiaries,Average Submitted Charge Amount,Average Medicare Payment Amount
0,1033112180,CHATTANOOGA,374211688,Maxillofacial Surgery,70355,X-ray imaging of teeth,25,25,104.400000,11.348000
1,1043302466,NASHVILLE,372320001,Diagnostic Radiology,70355,X-ray imaging of teeth,27,26,80.000000,7.824074
2,1104009646,KNOXVILLE,379201502,Maxillofacial Surgery,21248,Partial reconstruction of lower jaw or cheek b...,30,19,1970.000000,662.898333
3,1104009646,KNOXVILLE,379201502,Maxillofacial Surgery,70355,X-ray imaging of teeth,60,60,85.833333,13.701667
4,1104031053,NASHVILLE,372328605,Otolaryngology,21461,Open treatment of broken jaw bone,11,11,3614.000000,348.310000

In [9]:
#rename columns
cms_physician = cms_physician.rename(columns = {'National Provider Identifier':'provider_id',
                                                'City of the Provider':'city',
                                                'Zip Code of the Provider':'postal_code',
                                                'City of the Provider':'city',
                                                'State Code of the Provider':'state',
                                                'Provider Type':'treatment_type',
                                                'HCPCS Code':'hcpcs_code',
                                                'HCPCS Description':'description',
                                                'Number of Services':'services_performed',
                                                'Number of Medicare Beneficiaries':'beneficiaries',
                                                'Average Submitted Charge Amount':'avg_charge_submitted',
                                                'Average Medicare Payment Amount':'avg_medicare payment'
                                               })
cms_physician.head()

,provider_id,city,postal_code,treatment_type,hcpcs_code,description,services_performed,beneficiaries,avg_charge_submitted,avg_medicare payment
0,1033112180,CHATTANOOGA,374211688,Maxillofacial Surgery,70355,X-ray imaging of teeth,25,25,104.400000,11.348000
1,1043302466,NASHVILLE,372320001,Diagnostic Radiology,70355,X-ray imaging of teeth,27,26,80.000000,7.824074
2,1104009646,KNOXVILLE,379201502,Maxillofacial Surgery,21248,Partial reconstruction of lower jaw or cheek b...,30,19,1970.000000,662.898333
3,1104009646,KNOXVILLE,379201502,Maxillofacial Surgery,70355,X-ray imaging of teeth,60,60,85.833333,13.701667
4,1104031053,NASHVILLE,372328605,Otolaryngology,21461,Open treatment of broken jaw bone,11,11,3614.000000,348.310000

In [10]:
#export to csv
cms_physician.to_csv('../cms_physician.csv', index = False)

In [11]:
cms_physician.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   provider_id           95 non-null     int64
 1   city                  95 non-null     object
 2   postal_code           95 non-null     int64
 3   treatment_type        95 non-null     object
 4   hcpcs_code            95 non-null     int64
 5   description           95 non-null     object
 6   services_performed    95 non-null     int64
 7   beneficiaries         95 non-null     int64
 8   avg_charge_submitted  95 non-null     float64
 9   avg_medicare payment  95 non-null     float64
dtypes: float64(2), int64(5), object(3)
memory usage: 7.5+ KB